---
# Handlers for pterodactyl-apache-proxy role

- name: Restart apache2
  ansible.builtin.systemd:
    name: apache2
    state: restarted

- name: Restart wings
  ansible.builtin.systemd:
    name: wings
    state: restarted
