---
- name: Install prometheus-node-exporter
  ansible.builtin.apt:
    name: prometheus-node-exporter
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Configure node_exporter defaults
  ansible.builtin.copy:
    content: |
      ARGS="--web.listen-address={{ node_exporter_listen_address }}"
    dest: /etc/default/prometheus-node-exporter
    owner: root
    group: root
    mode: "0644"
  notify: restart node_exporter

- name: Enable and start node_exporter
  ansible.builtin.systemd:
    name: prometheus-node-exporter
    enabled: true
    state: started
